spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app
  data:
    redis:
      host: localhost
      port: 6379

app:
  jwt:
    secret: "CHANGE_ME_TO_A_RANDOM_64+_CHAR_SECRET_IN_PRODUCTION_USE_ENV_VAR_OR_SECRET_MANAGER"
    expirationSeconds: 3600
    issuer: "ecom-api"