spring:
  datasource:
    url: jdbc:mysql://mysql:3306/shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app
  data:
    redis:
      host: redis
      port: 6379
